local data={}
data.cards = {
	["metris"]={
		["murder"]={
			["ambush"]={
				["level"]=3,
				["exp"]=0,
			},
			["coupdegrace"]={
				["level"]=3,
				["exp"]=0,
			},
			["belladonna"]={
				["level"]=3,
				["exp"]=0,
			},
			["barrelbomb"]={
				["level"]=3,
				["exp"]=0,
			},
			["infighting"]={
				["level"]=3,
				["exp"]=0,
			},
			["arsenic"]={
				["level"]=3,
				["exp"]=0,
			},
			["mayhem"]={
				["level"]=3,
				["exp"]=0,
			},
			["satchelbomb"]={
				["level"]=3,
				["exp"]=0,
			},
			["waylay"]={
				["level"]=3,
				["exp"]=0,
			},
			["hemlock"]={
				["level"]=3,
				["exp"]=0,
			},
			["wagonbomb"]={
				["level"]=3,
				["exp"]=0,
			},
			["arson"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		
		["underlings"]={
			["brute"]={
				["level"]=3,
				["exp"]=0,
			},
			["assassin"]={
				["level"]=3,
				["exp"]=0,
			},
			["informant"]={
				["level"]=3,
				["exp"]=0,
			},
			["apothecary"]={
				["level"]=3,
				["exp"]=0,
			},
			["lackey"]={
				["level"]=3,
				["exp"]=0,
			},
			["charlatan"]={
				["level"]=3,
				["exp"]=0,
			},
			["bodyguard"]={
				["level"]=3,
				["exp"]=0,
			},
			["tavernwench"]={
				["level"]=3,
				["exp"]=0,
			},
			["cutpurse"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["espionage"]={
			["forgery"]={
				["level"]=3,
				["exp"]=0,
			},
			["roberry"]={
				["level"]=3,
				["exp"]=0,
			},
			["impersonate"]={
				["level"]=3,
				["exp"]=0,
			},
			["misinformation"]={
				["level"]=3,
				["exp"]=0,
			},
			["sabotage"]={
				["level"]=3,
				["exp"]=0,
			},
			["burglary"]={
				["level"]=3,
				["exp"]=0,
			},
			["surveillance"]={
				["level"]=3,
				["exp"]=0,
			},
			["stolenplans"]={
				["level"]=3,
				["exp"]=0,
			},
			["ramsack"]={
				["level"]=3,
				["exp"]=0,
			},
			["embezzle"]={
				["level"]=3,
				["exp"]=0,
			},
			["reconnaissance"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["conspiracy"]={
			["curryfavor"]={
				["level"]=3,
				["exp"]=0,
			},
			["consolidate"]={
				["level"]=3,
				["exp"]=0,
			},
			["subterfuge"]={
				["level"]=3,
				["exp"]=0,
			},
			["infiltrate"]={
				["level"]=3,
				["exp"]=0,
			},
			["misdirect"]={
				["level"]=3,
				["exp"]=0,
			},
			["deceit"]={
				["level"]=3,
				["exp"]=0,
			},
			["undermine"]={
				["level"]=3,
				["exp"]=0,
			},
			["frame"]={
				["level"]=3,
				["exp"]=0,
			},
			["coordinate"]={
				["level"]=3,
				["exp"]=0,
			},
			["cleverplanning"]={
				["level"]=3,
				["exp"]=0,
			},
			["seduce"]={
				["level"]=3,
				["exp"]=0,
			},
			["stratagem"]={
				["level"]=3,
				["exp"]=0,
			},
		},
	},
	["endazu"]={
		["inscriptions"]={
			["empoweringseal"]={
				["level"]=3,
				["exp"]=0,
			},
			["papervipers"]={
				["level"]=3,
				["exp"]=0,
			},
			["scrollofpetals"]={
				["level"]=3,
				["exp"]=0,
			},
			["engravedurn"]={
				["level"]=3,
				["exp"]=0,
			},
			["wardingcircle"]={
				["level"]=3,
				["exp"]=0,
			},
			["tomeofmemory"]={
				["level"]=3,
				["exp"]=0,
			},
			["enchantedtreaty"]={
				["level"]=3,
				["exp"]=0,
			},
			["unstablerunes"]={
				["level"]=3,
				["exp"]=0,
			},
			["gravecontract"]={
				["level"]=3,
				["exp"]=0,
			},
			["lanternscroll"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		
		["anima"]={
			["golem"]={
				["level"]=3,
				["exp"]=0,
			},
			["gildedwarriors"]={
				["level"]=3,
				["exp"]=0,
			},
			["underworldbarge"]={
				["level"]=3,
				["exp"]=0,
			},
			["theyarakeen"]={
				["level"]=3,
				["exp"]=0,
			},
			["gildedscribes"]={
				["level"]=3,
				["exp"]=0,
			},
			["twilightpeacock"]={
				["level"]=3,
				["exp"]=0,
			},
			["gildedgeneral"]={
				["level"]=3,
				["exp"]=0,
			},
			["argorethflower"]={
				["level"]=3,
				["exp"]=0,
			},
			["hedgeguardian"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["goetia"]={
			["bloodpact"]={
				["level"]=3,
				["exp"]=0,
			},
			["veilwarden"]={
				["level"]=3,
				["exp"]=0,
			},
			["zamgizar"]={
				["level"]=3,
				["exp"]=0,
			},
			["bishmog"]={
				["level"]=3,
				["exp"]=0,
			},
			["ibshuk"]={
				["level"]=3,
				["exp"]=0,
			},
			["merchantoftime"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		
		["incantations"]={
			["haltingrebuke"]={
				["level"]=3,
				["exp"]=0,
			},
			["summoningrift"]={
				["level"]=3,
				["exp"]=0,
			},
			["cantillation"]={
				["level"]=3,
				["exp"]=0,
			},
			["poemofblight"]={
				["level"]=3,
				["exp"]=0,
			},
			["odashirsecho"]={
				["level"]=3,
				["exp"]=0,
			},
			["wordofunmaking"]={
				["level"]=3,
				["exp"]=0,
			},
			["whisperedbarbs"]={
				["level"]=3,
				["exp"]=0,
			},
			["banishinggust"]={
				["level"]=3,
				["exp"]=0,
			},
			["songofspring"]={
				["level"]=3,
				["exp"]=0,
			},
			["beholdtheveil"]={
				["level"]=3,
				["exp"]=0,
			},
		},
	},

	["vespitole"]={
		["prosperity"]={
			["serf"]={
				["level"]=3,
				["exp"]=0,
			},
			["merchantsguild"]={
				["level"]=3,
				["exp"]=0,
			},
			["loan"]={
				["level"]=3,
				["exp"]=0,
			},
			["wealthypatron"]={
				["level"]=3,
				["exp"]=0,
			},
			["vintner"]={
				["level"]=3,
				["exp"]=0,
			},
			["tithe"]={
				["level"]=3,
				["exp"]=0,
			},
			["spiceroute"]={
				["level"]=3,
				["exp"]=0,
			},
			["harvest"]={
				["level"]=3,
				["exp"]=0,
			},
			["tradecompany"]={
				["level"]=3,
				["exp"]=0,
			},
			["banker"]={
				["level"]=3,
				["exp"]=0,
			},
			["fief"]={
				["level"]=3,
				["exp"]=0,
			},
			["collecttaxes"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		
		["power"]={
			["spynetwork"]={
				["level"]=3,
				["exp"]=0,
			},
			["embargo"]={
				["level"]=3,
				["exp"]=0,
			},
			["masqueradeball"]={
				["level"]=3,
				["exp"]=0,
			},
			["corruption"]={
				["level"]=3,
				["exp"]=0,
			},
			["courtesan"]={
				["level"]=3,
				["exp"]=0,
			},
			["bounty"]={
				["level"]=3,
				["exp"]=0,
			},
			["usury"]={
				["level"]=3,
				["exp"]=0,
			},
			["bureaucrat"]={
				["level"]=3,
				["exp"]=0,
			},
			["courtlyintrigue"]={
				["level"]=3,
				["exp"]=0,
			},
			["tribute"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		
		["war"]={
			["palisade"]={
				["level"]=3,
				["exp"]=0,
			},
			["leadofcharge"]={
				["level"]=3,
				["exp"]=0,
			},
			["rampart"]={
				["level"]=3,
				["exp"]=0,
			},
			["ballista"]={
				["level"]=3,
				["exp"]=0,
			},
			["mercenary"]={
				["level"]=3,
				["exp"]=0,
			},
			["catapult"]={
				["level"]=3,
				["exp"]=0,
			},
			["marshall"]={
				["level"]=3,
				["exp"]=0,
			},
			["soldier"]={
				["level"]=3,
				["exp"]=0,
			},
			["warship"]={
				["level"]=3,
				["exp"]=0,
			},
			["knight"]={
				["level"]=3,
				["exp"]=0,
			},
			["militia"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["faith"]={
			["inquisitor"]={
				["level"]=3,
				["exp"]=0,
			},
			["sibyllinescrolls"]={
				["level"]=3,
				["exp"]=0,
			},
			["devotion"]={
				["level"]=3,
				["exp"]=0,
			},
			["bishop"]={
				["level"]=3,
				["exp"]=0,
			},
			["benediction"]={
				["level"]=3,
				["exp"]=0,
			},
			["holywrath"]={
				["level"]=3,
				["exp"]=0,
			},
			["liturgy"]={
				["level"]=3,
				["exp"]=0,
			},
			["prayer"]={
				["level"]=3,
				["exp"]=0,
			},
			["malediction"]={
				["level"]=3,
				["exp"]=0,
			},
			["synod"]={
				["level"]=3,
				["exp"]=0,
			},
			["miracle"]={
				["level"]=3,
				["exp"]=0,
			},
			["supplicant"]={
				["level"]=3,
				["exp"]=0,
			},
		},
	},
	
	["daramek"]={
		["idols"]={
			["sacredtortoise"]={
				["level"]=3,
				["exp"]=0,
			},
			["sacrificialdais"]={
				["level"]=3,
				["exp"]=0,
			},
			["shrineofrebirth"]={
				["level"]=3,
				["exp"]=0,
			},
			["serpentaltar"]={
				["level"]=3,
				["exp"]=0,
			},
			["shepherdsgift"]={
				["level"]=3,
				["exp"]=0,
			},
			["boarfetish"]={
				["level"]=3,
				["exp"]=0,
			},
			["herdingstones"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["rituals"]={
			["ceremonialdance"]={
				["level"]=3,
				["exp"]=0,
			},
			["riteofcambat"]={
				["level"]=3,
				["exp"]=0,
			},
			["repopulate"]={
				["level"]=3,
				["exp"]=0,
			},
			["festival"]={
				["level"]=3,
				["exp"]=0,
			},
			["carnage"]={
				["level"]=3,
				["exp"]=0,
			},
			["bloodlust"]={
				["level"]=3,
				["exp"]=0,
			},
			["culltheherd"]={
				["level"]=3,
				["exp"]=0,
			},
			["riteofpassage"]={
				["level"]=3,
				["exp"]=0,
			},
			["riteofbrood"]={
				["level"]=3,
				["exp"]=0,
			},
			["feast"]={
				["level"]=3,
				["exp"]=0,
			},
			["fertilityoffering"]={
				["level"]=3,
				["exp"]=0,
			},
			["ritualslaughter"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["slaves"]={
			["sacrificiallamb"]={
				["level"]=3,
				["exp"]=0,
			},
			["overseer"]={
				["level"]=3,
				["exp"]=0,
			},
			["starvingmob"]={
				["level"]=3,
				["exp"]=0,
			},
			["stampede"]={
				["level"]=3,
				["exp"]=0,
			},
			["orphangang"]={
				["level"]=3,
				["exp"]=0,
			},
			["shepherd"]={
				["level"]=3,
				["exp"]=0,
			},
			["goldpanner"]={
				["level"]=3,
				["exp"]=0,
			},
			["lepers"]={
				["level"]=3,
				["exp"]=0,
			},
			["scrivener"]={
				["level"]=3,
				["exp"]=0,
			},
			["ratcatcher"]={
				["level"]=3,
				["exp"]=0,
			},
			["scavengers"]={
				["level"]=3,
				["exp"]=0,
			},
		},
		["herd"]={
			["herdofaurochs"]={
				["level"]=3,
				["exp"]=0,
			},
			["colossalaurochs"]={
				["level"]=3,
				["exp"]=0,
			},
			["boarunguent"]={
				["level"]=3,
				["exp"]=0,
			},
			["aurochselixir"]={
				["level"]=3,
				["exp"]=0,
			},
			["direboar"]={
				["level"]=3,
				["exp"]=0,
			},
			["warrats"]={
				["level"]=3,
				["exp"]=0,
			},
			["goatpoultice"]={
				["level"]=3,
				["exp"]=0,
			},
			["herdofrats"]={
				["level"]=3,
				["exp"]=0,
			},
			["goatoutrider"]={
				["level"]=3,
				["exp"]=0,
			},
			["herdofboars"]={
				["level"]=3,
				["exp"]=0,
			},
			["ratointment"]={
				["level"]=3,
				["exp"]=0,
			},
			["herdofgoats"]={
				["level"]=3,
				["exp"]=0,
			},
		},
	},
}


data.coins = {
		
		"bantlingcrown",
		"vicardoubloon",
		"wergeldseax",
		"wishingcoin",
		"foolsgeld",
		"swindlersmark",
		"serpentsseal",
		"championspaiza",
		"kongregate",
		"fecundcharm",
		"gravelinedrachm",
		"ferrymanstoll",
		"divinercharms",
		"humblebundle",
		"crossandpile",
		"obolcornucopia"
}

data.heros = {	
	vespitole ={
		
			["regentmarsh"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["sofocatro"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["ysadora"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["cardinalpocci"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["madamaline"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["captainviatrix"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
		},
	metris ={
			["gretta"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["valdorian"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["theodox"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["loquori"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["birondelle"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},

	},
	daramek ={
			["babarus"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["esra"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["orom"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["tazin"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["mogesh"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["liet"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
	},
	endazu ={

			["jesmai"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["calipeth"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["zalasair"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
			["raktabaan"]={
				["level"]=3,
				["exp"]=0,
				["lib"]={},
				["deck"]={},
			},
		
	},
}

data.currentHero = {id="captainviatrix",faction = "vespitole"}
return data