local data = {
	faction = "metris",
	hero = "birondelle",
	["lib"]={
		[2]={
			["level"]=3,
			["id"]="ramsack",
			["category"]="espionage",
			["exp"]=0,
			["faction"]="metris",
		},
		[5]={
			["level"]=3,
			["id"]="deceit",
			["category"]="conspiracy",
			["exp"]=0,
			["faction"]="metris",
		},
		[4]={
			["level"]=3,
			["id"]="seduce",
			["category"]="conspiracy",
			["exp"]=0,
			["faction"]="metris",
		},
		[10]={
			["level"]=2,
			["id"]="stolenplans",
			["category"]="espionage",
			["exp"]=0,
			["faction"]="metris",
		},
		[9]={
			["level"]=3,
			["id"]="mayhem",
			["category"]="murder",
			["exp"]=0,
			["faction"]="metris",
		},
		[8]={
			["level"]=2,
			["id"]="seduce",
			["category"]="conspiracy",
			["exp"]=0,
			["faction"]="metris",
		},
		[3]={
			["level"]=3,
			["id"]="stolenplans",
			["category"]="espionage",
			["exp"]=0,
			["faction"]="metris",
		},
		[7]={
			["level"]=3,
			["id"]="stratagem",
			["category"]="conspiracy",
			["exp"]=0,
			["faction"]="metris",
		},
		[1]={
			["level"]=3,
			["id"]="waylay",
			["category"]="murder",
			["exp"]=0,
			["faction"]="metris",
		},
		[6]={
			["level"]=3,
			["id"]="roberry",
			["category"]="espionage",
			["exp"]=0,
			["faction"]="metris",
		},
	},
}


return data