local data = {
	faction = "vespitole",
	hero = "ysadora",
	["lib"]={
		[1]={
			["level"]=3,
			["exp"]=0,
			["category"]="power",
			["faction"]="vespitole",
			["id"]="courtlyintrigue",
		},
		[2]={
			["level"]=3,
			["exp"]=0,
			["category"]="faith",
			["faction"]="vespitole",
			["id"]="bishop",
		},
		[3]={
			["level"]=3,
			["exp"]=1,
			["category"]="power",
			["faction"]="vespitole",
			["id"]="usury",
		},
		[4]={
			["level"]=3,
			["exp"]=0,
			["category"]="war",
			["faction"]="vespitole",
			["id"]="marshall",
		},
		[5]={
			["level"]=3,
			["exp"]=0,
			["category"]="power",
			["faction"]="vespitole",
			["id"]="masqueradeball",
		},
		[6]={
			["level"]=3,
			["exp"]=0,
			["category"]="faith",
			["faction"]="vespitole",
			["id"]="supplicant",
		},
		[7]={
			["level"]=2,
			["exp"]=0,
			["category"]="power",
			["faction"]="vespitole",
			["id"]="courtlyintrigue",
		},
		[8]={
			["level"]=3,
			["exp"]=0,
			["category"]="prosperity",
			["faction"]="vespitole",
			["id"]="loan",
		},
		[9]={
			["level"]=2,
			["exp"]=0,
			["category"]="prosperity",
			["faction"]="vespitole",
			["id"]="loan",
		},
		[10]={
			["level"]=3,
			["exp"]=0,
			["category"]="war",
			["faction"]="vespitole",
			["id"]="ballista",
		},
	},
}



return data